### ISSUE TITLE
[Suggestions] Use Ajax to avoid page refresh.

### ISSUE THREAD

**Issue by yyjlincoln** [solved-chinese/app#21]
Please use Ajax to avoid page refresh, which can also improve the user experience.
ref: http://www.solvedchinese.org/learning/C0001/

Also, if possible, use HTTPS to improve data security.

**Comment by chenyx512** [comment]
Could you specify what to use Ajax on? 
My current design is to use Ajax only within review, and submit form and do full page refresh whenever user clicks the next button.
In the future, we may do a Ajax call for a smoother transition. Is it what you mean?

**Comment by chenyx512** [comment]
Https will definitely be added. It is just that the website is so under finished and we don’t actually have much time to do deployment things.

**Comment by yyjlincoln** [comment]
You can use Ajax to replace chinese characters and images, instead of refreshing the whole page. For example:

```
<html>
Some code here

<div id="ajax">
    Chinese Character
</div>

Some code here

<script>
    $("#ajax").text("Another Chinese Character")
</script>

</html>
```

**Comment by chenyx512** [comment]
Thanks for the suggestion. 
This method has been considered but we don’t have many front end devs for now, and the dynamic radical display makes front end render a bit hard as well. Also the next function right now is simply a easier way for admins to check characters before we have the learning/review pages.
