### ISSUE TITLE
Mislabeled pictures on GDrive

### ISSUE THREAD

**Issue by linxuanm** [solved-chinese/app#41]
It seems that numerous pictures' ID on GDrive is currently mislabeled, leading to the displaying of incorrect characters on the study set page.

<img width="846" alt="Screen Shot 2020-04-28 at 11 57 25 AM" src="https://user-images.githubusercontent.com/20480038/80852677-f6941080-8c5c-11ea-9aa6-59b920111cfb.png">

**Comment by chenyx512** [comment]
solved already
