### ISSUE TITLE
Learning Character is_view if statement

### ISSUE THREAD

**Issue by carlguo866** [solved-chinese/app#7]
in `learning_character_pure.html` [line 36](https://github.com/chenyx512/Jiezi/blob/master/jiezi/templates/learning/learning_character_pure.html) to line 92 puts all the buttons on the banner in an if statement. Because we need CFL to view the `/learning/C0001.html` file, it would show up for them and confuses them. Consider removing the if statement.

**Comment by chenyx512** [comment]
We are in the process of total reconstruction, and we will not change anything in the old code or develop new feature on it.
